# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  port = 8916
  apiUrl = "/.netlify/functions"
  title = "Redwood Tutorial Blog"
[api]
  port = 8915
[browser]
  open = true
[experimental]
  esbuild = false
